title: Wise Hedgehog Studio
email: info@wisehedgehog.studio
description: >
  A small indie game and app development studio
baseurl: ""
url: "https://wisehedgehog.studio"
twitter_username: wise_hedgehog

google_analytics: UA-104711057-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed



port: 4001

exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock

collections:
  projects:
    output: true
